#bin/sh
echo "Intro: why Kotlin ✓"
read -p ""
echo "Démo: diff Verbosité Java vs Kotlin ✓"
read -p ""
echo "Java and Kotlin work together ✓"
read -p ""
echo "Basics syntax : Immutabilité/code concis (val/var, data classes, ...) ✓"
read -p ""
echo "Properties: Riadh (vite fait) ✓"
read -p ""
echo "Statements vs expressions ✓"
read -p ""
echo "Null Saftey (Safe null access, Elvis operator, ...) ✓"
read -p ""
echo "Collections OK (Vite fait) ✓"
read -p ""
echo "Equality Ok Speak about orally ✓"
read -p ""
echo "Pattern Matching ✓"
read -p ""
echo "Sealed classes ✓"
read -p ""
echo "Functions : Vite fait ✓"
read -p ""
echo "Extension function ✓"
read -p ""
echo "Operator overloading ✓"
read -p ""
echo "Companion objects ✓"
read -p ""
echo "Standard library functions (apply, let, also) ✓"
read -p ""
echo "Class delegation ✓"
read -p ""
echo "Exception handlings ✓"
read -p ""
echo "Functional Programming (Closures, Function composition, Inline functions, Currying and partial application, Memoization, Either, ...) ✓"
read -p ""
echo "Generics(Parameterised functions, Parameterized types, Invariance, Covariance, Covariant return, Contravariance) ✓"
read -p ""
echo "Custom DSLs (Infix functions as keywords, Using function receivers in a DSL): En fonction du temps restant ✓"
read -p ""
echo "Conclusion ✓"
read -p ""
echo "Thank you for your attention ! ✓"
