#bin/sh
echo "Intro: why Kotlin ✓"
read -p ""
echo "Démo: diff Verbosité Java vs Kotlin ✓"
read -p ""
echo "Java and Kotlin work together : Riadh ✓"
read -p ""
echo "Basics syntax : Immutabilité/code concis (val/var, data classes, ...) Riadh" OK
read -p ""
echo "Properties: Riadh (vite fait)"
read -p ""
echo "Statements vs expressions: Riadh: OK"
read -p ""
echo "Null Saftey (Safe null access, Elvis operator, ...): Riadh: OK"
read -p ""
echo "Collections OK (Vite fait): Riadh"
read -p ""
echo "Equality Ok Speak about orally: OK Riadh"
read -p ""
echo "Pattern Matching OK Riadh"
read -p ""
echo "Sealed classes OK"
read -p ""
echo "Functions : Vite fait : OK Riadh"
read -p ""
echo "Extension function: Riadh OK..."
read -p ""
echo "Operator overloading: Riadh OK"
read -p ""
echo "Companion objects : Riadh vite fait (à voir)"
read -p ""
echo "Standard library functions (apply, let, also)"
read -p ""
echo "Class delegation"
read -p ""
echo "Exception handlings"
read -p ""
echo "Functional Programming (Closures, Function composition, Inline functions, Currying and partial application, Memoization, Either, ...)"
read -p ""
echo "Generics(Parameterised functions, Parameterized types, Invariance, Covariance, Covariant return, Contravariance) Vite fait"
read -p ""
echo "Custom DSLs (Infix functions as keywords, Using function receivers in a DSL): En fonction du temps restant"
read -p ""
echo "Conclusion: Riadh"
read -p ""
echo "Thank you for your attention !"
